---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары 
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре 
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины 
  - Пользователь должен иметь возможность добавлять товары в корзину и продолжить выбирать товары в каталоге
  - Пользователь должен видеть в каталоге название, рейтинг, цену со скидкой и без для всех товаров
  - Пользователь должен видеть на странице товара название, рейтинг, цену со скидкой и без для всех товаров
  - Пользователь должен просматривать каталог, пользуясь постраничным выводом
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность оформить заказ
  - Пользователь должен иметь возможность после оформления заказа перейти на страницу оплаты
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах 
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Корзина должна храниться в сессии браузера
  - Сайт представляет из себя SPA приложение и не должен перезагружать страницу
implicit:
 - Необходимо наличие формы регистрации пользователя
 - Необходима авторизация пользователя перед оформлением заказа
  
